// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Azure.StorageTypeProvider.Runtime")>]
[<assembly: AssemblyProductAttribute("FSharp.Azure.StorageTypeProvider")>]
[<assembly: AssemblyDescriptionAttribute("Allows easy access to Azure Storage assets through F# scripts.")>]
[<assembly: AssemblyVersionAttribute("2.0.1")>]
[<assembly: AssemblyFileVersionAttribute("2.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Azure.StorageTypeProvider.Runtime"
    let [<Literal>] AssemblyProduct = "FSharp.Azure.StorageTypeProvider"
    let [<Literal>] AssemblyDescription = "Allows easy access to Azure Storage assets through F# scripts."
    let [<Literal>] AssemblyVersion = "2.0.1"
    let [<Literal>] AssemblyFileVersion = "2.0.1"
