#r @"..\..\bin\FSharp.Azure.StorageTypeProvider.dll"
#r @"..\..\bin\Microsoft.Data.OData.dll"
#r @"..\..\bin\Microsoft.Data.Services.Client.dll"
#r @"..\..\bin\Microsoft.Data.Edm.dll"
#r @"..\..\bin\Microsoft.Azure.Storage.dll"
#r @"..\..\bin\Newtonsoft.Json.dll"
#r @"..\..\bin\System.Spatial.dll"
#r @"System.Xml.Linq.dll"
#r @"..\..\packages\Deedle\lib\net40\Deedle.dll"
do fsi.AddPrinter(fun (printer:Deedle.Internal.IFsiFormattable) -> "\n" + (printer.Format()))
#load @"..\..\tests\integrationtests\ResetTestData.fsx"
